language: c

branches:
  except:
    - /^feature.*$/

env:
  global:
   # The next declaration is the encrypted COVERITY_SCAN_TOKEN, created
   #   via the "travis encrypt" command using the project repo's public key
    - secure: "H5vV5Ph2p3LyWtvPgAGh1H+B9zVAd1ogwwcj9QRmloKDkOeHqAlZ1s3g/kiMY5sHuNZel580OGbXaorYR5Uj6SpVveWcwDeLpjdGtJrr+lhZkcK/mAapWTjop3+xWwBUeQv3SpK+UgqfYJ8CVR4Kho5qs+q/FCiqCJc9rkan0Tc="
  matrix:
    - BUILD=gcc

before_script:
  - mkdir build
  - cd build

script:
  - if [ ${COVERITY_SCAN_BRANCH} != 1 ]; then
      case ${BUILD} in
        gcc)
          cmake ..  &&
          make
          ;;
      esac ;
    fi

addons:
  coverity_scan:
    project:
      name: "gatzka/cJSON"
      description: "Build submitted via Travis CI"
    notification_email: stephan.gatzka@gmail.com
    build_command_prepend: "cmake ../"
    build_command: "make"
    branch_pattern: coverity_scan
